### ISSUE TITLE
Projects with more than a handful of files crash the editor

### ISSUE THREAD

**Issue by jobbogamer** [UoYCS-plasma/GP2-editor#58]
I have a GP2 project which contains 23 files:
- 1 `.gpp` project file
- 14 `.gpr` rule files
- 6 program files (3 user-created `.gp2` files and 3 compiled `.gp2.tmp` files)
- 2 `.host` graph files

When I try to open this project in the editor, it crashes and shows the following message in the command line:

```
QKqueueFileSystemWatcherEngine: cannot create pipe: Too many open files
QKqueueFileSystemWatcherEngine::addPaths: open: Too many open files
QFileSystemWatcher: failed to add paths: /Users/Josh/Dropbox/University/Project/GP2_Programs/TracingTest/graphs/clean.host
QEventDispatcherUNIXPrivate(): Unable to create thread pipe: Too many open files
QEventDispatcherUNIXPrivate(): Can not continue without a thread pipe
Unknown error while opening file:  "/Users/Josh/Dropbox/University/Project/GP2_Programs/TracingTest/graphs/clean.host" 
Abort trap: 6           ./gpdeveloper
```

I don't know if this is a Qt issue or a GP2 issue. If I manually edit the `.gpp` file and remove a reference to one file, I am able to open the project again, suggesting the limit is 22 files.

**Comment by jobbogamer** [comment]
I should note, this is on macOS 10.12 – hence the mention of UNIX in the error message. I have 24 GB of RAM so I don't think that's the issue.

**Comment by ivaylohristakiev** [comment]
After initial digging it looks like a Qt4 internal issue on macOS.

Try updating the open file limit via terminal:
`ulimit -S -n 8048`

**Comment by jobbogamer** [comment]
Yes, increasing the file limit does allow me to open the project. I don't know if you want to consider this issue closed or not, it's up to you.

**Comment by ivaylohristakiev** [comment]
Increasing the fault  tolerance of the Editor is the real issue here, internal issues of the Qt library shouldn't cause silent failures. #59
