### ISSUE TITLE
MacOS Has No Delete Key

### ISSUE THREAD

**Issue by GrahamCampbell** [UoYCS-plasma/GP2-editor#62]
Would it be possible to hookup the backspace key to behave the same as a delete key, so that it can delete nodes. Whereabouts in the codebase are the key bindings setup?

**Comment by ivaylohristakiev** [comment]
I am unsure, but try 
[here](https://github.com/UoYCS-plasma/GP2-editor/blob/5b57b634eab23d69655985099cdc14026398c70c/src/developer/graphview/graphscene.cpp#L912)
